### ISSUE TITLE
Reload of script does not work in interactive mode

### ISSUE THREAD

**Issue by mzorec** [flubu-core/flubu.core#351]
ERROR: System.Reflection.TargetException: Object does not match target type.
   at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Reflection.PropertyInfo.GetValue(Object obj)
   at FlubuCore.Context.BuildPropertiesSession.GetValueFromPropertyInfo[T](String propertyName) in c:\jenkins\workspace\FlubuCore\src\FlubuCore\Context\BuildPropertiesSession.cs:line 252
   at FlubuCore.Context.BuildPropertiesSession.Get[T](String propertyName, T defaultValue, String memberName) in c:\jenkins\workspace\FlubuCore\src\FlubuCore\Context\BuildPropertiesSession.cs:line 151

**Comment by mzorec** [comment]
Fixed. Didn't work when build property attributes were used in script.
